name: CI
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_user_data
        with:
          route: GET /users/{user}
          user: pawap90
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo user output: ${{ steps.get_user_data.outputs.data.blog }}"
